model_list:
  - model_name: x-ai/grok-4-fast
    litellm_params: 
      model: openrouter/x-ai/grok-4-fast
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 2000000
      max_output_tokens: 30000
      input_cost_per_token: 0.0000002
      output_cost_per_token: 0.0000005
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.00000005
      cache_creation_input_token_cost: 0
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  - model_name: x-ai/grok-4-fast-online
    litellm_params: 
      model: openrouter/x-ai/grok-4-fast:online
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 2000000
      max_output_tokens: 30000
      input_cost_per_token: 0.0000002
      output_cost_per_token: 0.0000005
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.00000005
      cache_creation_input_token_cost: 0
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false